plugins {
    id 'base'
}

allprojects {
    group = providers.gradleProperty('group').get()
    version = providers.gradleProperty('version').get()

    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

subprojects {
    plugins.withId('maven-publish') {
        def gitlabMavenRepositoryUrl = providers.gradleProperty('gitlabMavenRepositoryUrl')

        if (gitlabMavenRepositoryUrl.isPresent()) {
            publishing {
                repositories {
                    maven {
                        name = 'GitLab'
                        url = uri(gitlabMavenRepositoryUrl.get())
                        credentials {
                            username = providers.gradleProperty('gitlabMavenUsername').getOrElse('gitlab-ci-token')
                            password = providers.gradleProperty('gitlabMavenToken').getOrElse('')
                        }
                    }
                }
            }
        }
    }
}
