plugins {
    id 'base'
}

allprojects {
    group = providers.gradleProperty('group').get()
    version = providers.gradleProperty('version').get()

    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

subprojects {
    pluginManager.withPlugin('maven-publish') {
        publishing {
            repositories {
                maven {
                    name = "GitHubPackages"

                    def repoUrl = project.findProperty("githubMavenRepositoryUrl")
                            ?: "https://maven.pkg.github.com/${System.getenv('GITHUB_REPOSITORY')}"
                    url = uri(repoUrl)

                    credentials {
                        username = System.getenv("GITHUB_ACTOR")
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
            }
        }
    }
}