import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'base'
    id 'io.gitlab.arturbosch.detekt' version '1.23.4' apply false
    id 'com.github.spotbugs' version '6.0.9' apply false
}

allprojects {
    group = providers.gradleProperty('group').get()
    version = providers.gradleProperty('version').get()

    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

subprojects {
    plugins.withId('org.jetbrains.kotlin.jvm') {
        apply plugin: 'io.gitlab.arturbosch.detekt'

        detekt {
            buildUponDefaultConfig = true
            autoCorrect = false
            parallel = true
            reports {
                html.required = true
                sarif.required = true
            }
            dependencies {
                detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.23.4"
            }
        }
    }

    plugins.withId('java') {

        apply plugin: 'checkstyle'
        checkstyle {
            toolVersion = '10.12.5'
            maxWarnings = 0
        }

        apply plugin: 'com.github.spotbugs'
        spotbugs {
            ignoreFailures = false
            showProgress = true
            effort = 'max'
            reportLevel = 'medium'
        }

        tasks.withType(SpotBugsTask).tap {
            configureEach {
                reports {
                    html.required = true
                    sarif.required = true
                }
            }
        }
    }

    pluginManager.withPlugin('maven-publish') {
        publishing {
            repositories {
                maven {
                    name = "GitHubPackages"

                    def repoUrl = project.findProperty("githubMavenRepositoryUrl")
                            ?: "https://maven.pkg.github.com/${System.getenv('GITHUB_REPOSITORY')}"
                    url = uri(repoUrl)

                    credentials {
                        username = System.getenv("GITHUB_ACTOR")
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
            }
        }
    }
}