name: Actions

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write
  pull-requests: write

jobs:
  call-template:
    uses: MaximShuvalov/infrastructure-ci-templates/.github/workflows/libs.yml@master
    with:
      java-version: '21'
      enable-ai-summary: true
    secrets:
      PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LLM_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}