name: Actions

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-template:
    uses: MaximShuvalov/infrastructure-ci-templates/.github/workflows/libs.yml@master
    with:
      java-version: '21'
    secrets:
      PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}